package com.ganatan.backend_java.modules.openAPI;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import java.util.List;

/**
 * DTO for the response from the OpenAI API.
 * This class represents the structure of the
 * JSON response returned by the API.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
public class OpenAIResponseDTO {

    /**
     * Unique identifier for the response.
     */
    private String id;

    /**
     * The type of object returned, typically
     * "chat.completion".
     */
    private String object;

    /**
     * Timestamp indicating when the response was created.
     */
    private long created;

    /**
     * The model used to generate the response.
     */
    private String model;

    /**
     * List of choices generated by the model
     * in response to the user input.
     */
    private List<Choice> choices;

    /**
     * Represents an individual choice in the response
     * from the OpenAI API.
     */
    @Data
    public static class Choice {

        /**
         * The index of the choice in the list
         * of generated choices.
         */
        private int index;

        /**
         * The message generated by the model
         * for this choice.
         */
        private Message message;

        /**
         * Log probabilities of the generated tokens,
         * can be null.
         */
        private Object logprobs;

        /**
         * Reason for the completion ending, can be null.
         */
        @JsonProperty("finish_reason")
        private String finishReason;
    }

    /**
     * Represents the message generated by
     * the OpenAI model.
     */
    @Data
    public static class Message {

        /**
         * The role of the sender.
         */
        private String role;

        /**
         * The content of the message
         * generated by the model.
         */
        private String content;

        /**
         * Optional refusal message if the
         * model cannot generate a response.
         */
        private Object refusal;
    }
}
